{
 "title": "Ubuntu Health",
 "tags": [
  "system",
  "ubuntu",
  "node_exporter"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU Usage (%)",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "gauge",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100"
    }
   ]
  },
  {
   "title": "Disk Usage (%)",
   "type": "gauge",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"tmpfs\"} - node_filesystem_free_bytes{mountpoint=\"/\",fstype!=\"tmpfs\"}) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"tmpfs\"} * 100"
    }
   ]
  },
  {
   "title": "Load Average (1m)",
   "type": "gauge",
   "gridPos": { "x": 18, "y": 0, "w": 6, "h": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1" }
   ]
  },
  {
   "title": "Network Traffic (Bytes/sec)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 6, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device!~\"lo|docker.*\"}[2m])",
     "legendFormat": "{{device}} RX"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device!~\"lo|docker.*\"}[2m])",
     "legendFormat": "{{device}} TX"
    }
   ]
  }
 ]
}